# Generated by Django 6.0.7 on 2026-08-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_operations", "0004_remove_communications_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="start time"
            ),
        ),
    ]
