# Generated by Django 6.0.7 on 2026-08-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_operations", "0006_attendance_excel_and_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceweekstat",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
