# Generated by Django 6.0.7 on 2026-08-06 20:45

import django.db.models.deletion
from django.db import migrations, models


def backfill_attendance_events(apps, schema_editor):
    """Ensure every AttendanceRecord has an Event."""
    Event = apps.get_model("cf_operations", "Event")
    AttendanceRecord = apps.get_model("cf_operations", "AttendanceRecord")
    AttendanceReport = apps.get_model("cf_operations", "AttendanceReport")

    # Link reports without events.
    for report in AttendanceReport.objects.filter(event__isnull=True):
        event = Event.objects.create(
            branch_id=report.branch_id,
            title=report.report_title or f"Attendance sheet {report.pk}",
            event_type="SERVICE",
            visibility="ORGANIZATION",
            description="Auto-created when linking attendance records to events.",
        )
        report.event_id = event.pk
        report.save(update_fields=["event_id"])

    for rec in AttendanceRecord.objects.filter(event__isnull=True).select_related(
        "report"
    ):
        event_id = None
        if rec.report_id and rec.report.event_id:
            event_id = rec.report.event_id
        if event_id is None:
            event = Event.objects.create(
                branch_id=rec.branch_id,
                title=rec.centre_name or f"Attendance {rec.pk}",
                event_type="SERVICE",
                visibility="ORGANIZATION",
                description="Auto-created for legacy attendance row.",
            )
            event_id = event.pk
        rec.event_id = event_id
        rec.save(update_fields=["event_id"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cf_operations", "0007_alter_attendanceweekstat_id"),
        ("cf_people", "0008_birthday_templates_and_drop_member_dob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ("-created_at", "serial_number", "centre_name"),
                "verbose_name": "attendance record",
                "verbose_name_plural": "attendance records",
            },
        ),
        # Preserve existing cell_group links as subgroup.
        migrations.RenameField(
            model_name="attendancerecord",
            old_name="cell_group",
            new_name="subgroup",
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="subgroup",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Cell / satellite under the zone.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="cf_people.subbranch",
                verbose_name="sub group",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="event",
            field=models.ForeignKey(
                help_text="The service, outreach, or gathering this attendance is for.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="cf_operations.event",
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Zone under the branch where attendance was taken.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="cf_people.zone",
                verbose_name="zone",
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Link this sheet to a service / outreach event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_reports",
                to="cf_operations.event",
                verbose_name="linked event",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="centre_name",
            field=models.CharField(
                blank=True,
                help_text="Cell / centre name as on the sheet (if not linked to a sub group).",
                max_length=255,
                verbose_name="centre name",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="report",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional Excel-style sheet this row belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="cf_operations.attendancereport",
                verbose_name="attendance report",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (all platform users)"),
                    ("ORGANIZATION", "Organisation only"),
                    ("BRANCH", "Branch only"),
                ],
                db_index=True,
                default="PUBLIC",
                help_text=(
                    "Public: anyone on the platform. Organisation only: all "
                    "branches of this church. Branch only: only this branch's users."
                ),
                max_length=20,
                verbose_name="visibility",
            ),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (all platform users)"),
                    ("ORGANIZATION", "Organisation only"),
                    ("BRANCH", "Branch only"),
                ],
                db_index=True,
                default="PUBLIC",
                help_text=(
                    "Public: anyone on the platform. Organisation only: all "
                    "branches of this church. Branch only: only this branch's users."
                ),
                max_length=20,
                verbose_name="visibility",
            ),
        ),
        migrations.RunPython(backfill_attendance_events, noop),
    ]
