# Generated by Django 6.0.7 on 2026-08-06 21:04

import cf_users.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_operations", "0008_event_visibility_branch_and_attendance_scope"),
        ("cf_users", "0007_birthday_templates_and_drop_member_dob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 1st Service, 2nd Service, Youth, Check-in",
                        max_length=150,
                        verbose_name="session name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this session begins.",
                        null=True,
                        verbose_name="start time",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this session ends.",
                        null=True,
                        verbose_name="end time",
                    ),
                ),
                (
                    "check_in_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. When check-in / attendance capture opens.",
                        null=True,
                        verbose_name="check-in start",
                    ),
                ),
                (
                    "check_in_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. When check-in / attendance capture closes.",
                        null=True,
                        verbose_name="check-in end",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="sort order",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Usually the same as the event branch (set automatically).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_sessions",
                        to="cf_users.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="cf_operations.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "event session",
                "verbose_name_plural": "event sessions",
                "ordering": ("event", "sort_order", "start_time", "name"),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Which session of the event (e.g. 1st service, 2nd service).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="cf_operations.eventsession",
                verbose_name="event session",
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Which session of the event this sheet covers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_reports",
                to="cf_operations.eventsession",
                verbose_name="event session",
            ),
        ),
    ]
