# Generated by Django 6.0.7 on 2026-08-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cf_operations", "0012_remove_legacy_attendance_report"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ("-modified_at", "serial_number", "centre_name"),
                "verbose_name": "attendance record",
                "verbose_name_plural": "attendance records",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ("-modified_at", "title"),
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
        migrations.AlterModelOptions(
            name="documentcategory",
            options={
                "ordering": ("-modified_at", "name"),
                "verbose_name": "document category",
                "verbose_name_plural": "document categories",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("-modified_at", "-start_time"),
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterModelOptions(
            name="sermon",
            options={
                "ordering": ("-modified_at",),
                "verbose_name": "sermon",
                "verbose_name_plural": "sermons",
            },
        ),
    ]
