# Generated by Django 6.0.7 on 2026-08-04 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cf_operations", "0001_initial"),
        ("cf_people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="cf_people.member",
                verbose_name="member",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="visitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="cf_people.visitor",
                verbose_name="visitor",
            ),
        ),
    ]
