# Generated by Django 6.0.7 on 2026-08-04 14:20

import cf_users.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="check-in time"
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance record",
                "verbose_name_plural": "attendance records",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "session_name",
                    models.CharField(max_length=100, verbose_name="session name"),
                ),
                ("check_in_start", models.DateTimeField(verbose_name="check-in start")),
                ("check_in_end", models.DateTimeField(verbose_name="check-in end")),
            ],
            options={
                "verbose_name": "attendance session",
                "verbose_name_plural": "attendance sessions",
                "ordering": ("check_in_start",),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="campaign title"),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Full message text used for email and in-app channels.",
                        verbose_name="body",
                    ),
                ),
                (
                    "sms_text",
                    models.TextField(
                        blank=True,
                        help_text="Condensed copy for SMS dispatch. Falls back to a truncated body if blank.",
                        null=True,
                        verbose_name="SMS copy",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text='e.g. ["email", "sms", "whatsapp"]',
                        verbose_name="channels",
                    ),
                ),
                (
                    "target_all",
                    models.BooleanField(
                        default=True, verbose_name="target all active members"
                    ),
                ),
                (
                    "only_active_members",
                    models.BooleanField(
                        default=True, verbose_name="active members only"
                    ),
                ),
                (
                    "target_absent_members",
                    models.BooleanField(
                        default=False,
                        help_text="If True, limits recipients to members absent for at least 'absence_days'.",
                        verbose_name="target absent members",
                    ),
                ),
                (
                    "absence_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum days since last attendance. Required when targeting absent members.",
                        null=True,
                        verbose_name="absence threshold (days)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "recipients_targeted",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="recipients targeted"
                    ),
                ),
                (
                    "recipients_sent",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="recipients sent"
                    ),
                ),
                (
                    "recipients_failed",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="recipients failed"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="sent at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "broadcast message",
                "verbose_name_plural": "broadcast messages",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="branch_documents/%Y/%m/",
                        verbose_name="file",
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(default=False, verbose_name="is confidential"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ("title",),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "required_role_access",
                    models.CharField(
                        default="VIEWER",
                        max_length=50,
                        verbose_name="required access role",
                    ),
                ),
            ],
            options={
                "verbose_name": "document category",
                "verbose_name_plural": "document categories",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "start_time",
                    models.DateTimeField(db_index=True, verbose_name="start time"),
                ),
                ("end_time", models.DateTimeField(verbose_name="end time")),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("NONE", "One-off"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="NONE",
                        max_length=10,
                        verbose_name="recurrence",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ("-start_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("alert", "Urgent / Alert"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=150, verbose_name="title"),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "seen",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="seen"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("IN_APP", "In-App"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        max_length=20,
                        verbose_name="channel",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subject / title"
                    ),
                ),
                (
                    "body_content",
                    models.TextField(
                        help_text="Supports Django template tag variables, e.g. {{ member.first_name }}.",
                        verbose_name="body content",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification template",
                "verbose_name_plural": "notification templates",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "scripture_reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g. John 3:16, Romans 8:28–30",
                        max_length=255,
                        verbose_name="scripture reference",
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="audio URL"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="video URL"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="sermon notes")),
            ],
            options={
                "verbose_name": "sermon",
                "verbose_name_plural": "sermons",
                "ordering": ("-created_at",),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
    ]
