# Generated by Django 6.0.7 on 2026-08-06 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_people", "0008_birthday_templates_and_drop_member_dob"),
        ("cf_social", "0001_initial_social_mvp"),
        ("cf_users", "0007_birthday_templates_and_drop_member_dob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or first post for this discussion.",
                        max_length=10000,
                        verbose_name="opening message",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("PLATFORM", "All platform users"),
                            ("ORGANIZATION", "Organisation"),
                            ("BRANCH", "Branch"),
                            ("ZONE", "Zone"),
                        ],
                        db_index=True,
                        default="PLATFORM",
                        help_text="Who can view and participate: entire platform, one organisation, one branch, or one zone.",
                        max_length=20,
                        verbose_name="audience",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="When locked, no new messages can be posted.",
                        verbose_name="locked",
                    ),
                ),
                (
                    "messages_count",
                    models.PositiveIntegerField(default=0, verbose_name="messages"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="last message at",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when audience is Branch (also set from Zone).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="cf_users.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when audience is Organisation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="cf_users.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when audience is Zone.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="cf_people.zone",
                        verbose_name="zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "discussion",
                "verbose_name_plural": "discussions",
                "ordering": ("-last_message_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="DiscussionMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("body", models.TextField(max_length=10000, verbose_name="body")),
                (
                    "is_hidden",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="hidden"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="cf_social.discussion",
                        verbose_name="discussion",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="cf_social.discussionmessage",
                        verbose_name="parent message",
                    ),
                ),
            ],
            options={
                "verbose_name": "discussion message",
                "verbose_name_plural": "discussion messages",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["audience", "-created_at"],
                name="cf_social_d_audienc_e8d002_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="cf_social_d_organiz_2921aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["branch", "-created_at"], name="cf_social_d_branch__ebeb55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["zone", "-created_at"], name="cf_social_d_zone_id_a393b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussionmessage",
            index=models.Index(
                fields=["discussion", "created_at"],
                name="cf_social_d_discuss_44a26e_idx",
            ),
        ),
    ]
