# Generated by Django 6.0.7 on 2026-08-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cf_social", "0002_discussion_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-modified_at", "created_at"),
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ("-last_message_at", "-modified_at"),
                "verbose_name": "conversation",
                "verbose_name_plural": "conversations",
            },
        ),
        migrations.AlterModelOptions(
            name="directmessage",
            options={
                "ordering": ("-modified_at", "created_at"),
                "verbose_name": "direct message",
                "verbose_name_plural": "direct messages",
            },
        ),
        migrations.AlterModelOptions(
            name="discussion",
            options={
                "ordering": ("-last_message_at", "-modified_at"),
                "verbose_name": "discussion",
                "verbose_name_plural": "discussions",
            },
        ),
        migrations.AlterModelOptions(
            name="discussionmessage",
            options={
                "ordering": ("-modified_at", "created_at"),
                "verbose_name": "discussion message",
                "verbose_name_plural": "discussion messages",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-modified_at",),
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ("-modified_at",),
                "verbose_name": "report",
                "verbose_name_plural": "reports",
            },
        ),
        migrations.AlterModelOptions(
            name="socialnotification",
            options={
                "ordering": ("-modified_at",),
                "verbose_name": "social notification",
                "verbose_name_plural": "social notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="socialprofile",
            options={
                "ordering": ("-modified_at",),
                "verbose_name": "social profile",
                "verbose_name_plural": "social profiles",
            },
        ),
    ]
