# Generated by Django 6.0.7 on 2026-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='System-generated organisation code (e.g. ORG00000001). Immutable.', max_length=32, null=True, unique=True, verbose_name='code'),
        ),
    ]
