# Generated by Django 6.0.7 on 2026-08-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_users", "0004_alter_organizationuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=20,
                null=True,
                verbose_name="gender",
            ),
        ),
    ]
