# Generated by Django 6.0.7 on 2026-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_users", "0005_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Used for verification, age groups, and birthday greetings.",
                null=True,
                verbose_name="birth date",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                max_length=20,
                null=True,
                verbose_name="gender",
            ),
        ),
    ]
