# Generated by Django 6.0.7 on 2026-08-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cf_users", "0007_birthday_templates_and_drop_member_dob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "ordering": ("-modified_at",),
                "verbose_name": "branch",
                "verbose_name_plural": "branches",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("-modified_at", "name"),
                "verbose_name": "organisation",
                "verbose_name_plural": "organisations",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("-modified_at", "last_name", "first_name"),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
