# Generated by Django 6.0.7 on 2026-08-04 14:20

import cf_users.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "member_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="member number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="middle name"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="date of birth",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "membership_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("TRANSFERRED", "Transferred"),
                            ("DECEASED", "Deceased"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="membership status",
                    ),
                ),
                (
                    "join_date",
                    models.DateField(blank=True, null=True, verbose_name="join date"),
                ),
            ],
            options={
                "verbose_name": "member",
                "verbose_name_plural": "members",
                "ordering": ("last_name", "first_name"),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DepartmentMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEADER", "Department Leader"),
                            ("ASSISTANT", "Assistant Leader"),
                            ("MEMBER", "Regular Member"),
                        ],
                        default="MEMBER",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
            ],
            options={
                "verbose_name": "department member",
                "verbose_name_plural": "department members",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "family_name",
                    models.CharField(max_length=255, verbose_name="family name"),
                ),
                (
                    "primary_phone",
                    models.CharField(max_length=30, verbose_name="primary phone"),
                ),
                ("home_address", models.TextField(verbose_name="home address")),
            ],
            options={
                "verbose_name": "family",
                "verbose_name_plural": "families",
                "ordering": ("family_name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "scheduled_date",
                    models.DateField(db_index=True, verbose_name="scheduled date"),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="completed date"
                    ),
                ),
                (
                    "outcome_notes",
                    models.TextField(blank=True, verbose_name="outcome notes"),
                ),
            ],
            options={
                "verbose_name": "follow-up",
                "verbose_name_plural": "follow-ups",
                "ordering": ("scheduled_date",),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        help_text="e.g. Father, Mother, Grandparent, Legal Guardian",
                        max_length=50,
                        verbose_name="relationship type",
                    ),
                ),
            ],
            options={
                "verbose_name": "guardian",
                "verbose_name_plural": "guardians",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("CELL", "Cell Group"),
                            ("ZONE", "Zone"),
                            ("SETTLITE", "Settlite Fellowship"),
                        ],
                        max_length=20,
                        verbose_name="group",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "cell group",
                "verbose_name_plural": "cell groups",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="phone number"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(db_index=True, verbose_name="visit date"),
                ),
                (
                    "conversion_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Follow-up"),
                            ("IN_PROGRESS", "Follow-up In Progress"),
                            ("CONVERTED", "Joined as Member"),
                            ("DECLINED", "Not Interested"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                        verbose_name="conversion status",
                    ),
                ),
            ],
            options={
                "verbose_name": "visitor",
                "verbose_name_plural": "visitors",
                "ordering": ("-visit_date",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChildProfile",
            fields=[
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="child_profile",
                        serialize=False,
                        to="cf_people.member",
                        verbose_name="member",
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(blank=True, verbose_name="medical notes"),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="allergies")),
                (
                    "check_in_pin",
                    models.CharField(
                        blank=True,
                        help_text="Secure PIN used by parents/guardians for child check-in authorisation.",
                        max_length=10,
                        verbose_name="check-in PIN",
                    ),
                ),
            ],
            options={
                "verbose_name": "child profile",
                "verbose_name_plural": "child profiles",
                "abstract": False,
            },
        ),
    ]
