# Generated by Django 6.0.7 on 2026-08-06 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_people", "0006_zone_and_subgroup_hierarchy"),
        ("cf_users", "0006_alter_user_birth_date_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="zone",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="zone",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Optional short code, e.g. Z13. Unique within the branch.",
                max_length=32,
                null=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(
                help_text="e.g. ZONE 13, Kasoa West. Unique within the branch.",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                fields=("branch", "name"), name="cf_people_zone_unique_branch_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("code__isnull", False), models.Q(("code", ""), _negated=True)
                ),
                fields=("branch", "code"),
                name="cf_people_zone_unique_branch_code",
            ),
        ),
    ]
