# Generated by Django 6.0.7 on 2026-08-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cf_people", "0008_birthday_templates_and_drop_member_dob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ("-modified_at", "name"),
                "verbose_name": "department",
                "verbose_name_plural": "departments",
            },
        ),
        migrations.AlterModelOptions(
            name="family",
            options={
                "ordering": ("-modified_at", "family_name"),
                "verbose_name": "family",
                "verbose_name_plural": "families",
            },
        ),
        migrations.AlterModelOptions(
            name="followup",
            options={
                "ordering": ("-modified_at", "scheduled_date"),
                "verbose_name": "follow-up",
                "verbose_name_plural": "follow-ups",
            },
        ),
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ("-modified_at", "user__last_name", "user__first_name"),
                "verbose_name": "member",
                "verbose_name_plural": "members",
            },
        ),
        migrations.AlterModelOptions(
            name="subbranch",
            options={
                "ordering": ("-modified_at", "zone", "name"),
                "verbose_name": "sub group",
                "verbose_name_plural": "sub groups",
            },
        ),
        migrations.AlterModelOptions(
            name="visitor",
            options={
                "ordering": ("-modified_at", "-visit_date"),
                "verbose_name": "visitor",
                "verbose_name_plural": "visitors",
            },
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={
                "ordering": ("-modified_at", "branch", "name"),
                "verbose_name": "zone",
                "verbose_name_plural": "zones",
            },
        ),
    ]
