# Generated by Django 6.0.7 on 2026-08-04 14:20

import cf_users.base.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="9–64 characters. Letters, digits, and one special character (_ or @) allowed, but not at the start. No spaces.",
                        max_length=64,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=64, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=64, verbose_name="last name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="middle name"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Primary contact number, e.g. +233201234567.",
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "phone_number2",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Optional backup number.",
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="alternative phone",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        help_text="Used for verification and age-group assignment.",
                        null=True,
                        verbose_name="birth date",
                    ),
                ),
                ("address", models.CharField(max_length=256, verbose_name="address")),
                ("city", models.CharField(max_length=64, verbose_name="city")),
                ("country", models.CharField(max_length=64, verbose_name="country")),
                (
                    "geo_address",
                    models.CharField(
                        blank=True,
                        help_text="Digital home address (e.g. Ghana Post GPS code).",
                        max_length=32,
                        null=True,
                        verbose_name="GPS address",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="company"
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="bio")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("en-us", "English (US)"),
                            ("fr", "French"),
                        ],
                        default="en-us",
                        max_length=8,
                        verbose_name="language",
                    ),
                ),
                (
                    "is_church_staff",
                    models.BooleanField(default=False, verbose_name="is church staff"),
                ),
                (
                    "notify_via_inapp",
                    models.BooleanField(default=True, verbose_name="notify via in-app"),
                ),
                (
                    "notify_via_email",
                    models.BooleanField(default=True, verbose_name="notify via email"),
                ),
                (
                    "notify_via_sms",
                    models.BooleanField(default=False, verbose_name="notify via SMS"),
                ),
                (
                    "notify_via_whatsapp",
                    models.BooleanField(
                        default=False, verbose_name="notify via WhatsApp"
                    ),
                ),
                (
                    "password_updated",
                    models.DateField(
                        blank=True, null=True, verbose_name="password updated"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="modified at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ("last_name", "first_name"),
                "abstract": False,
                "swappable": "AUTH_USER_MODEL",
            },
            managers=[
                ("objects", cf_users.base.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "branch_type",
                    models.CharField(
                        choices=[
                            ("PARENT", "Parent / Main Campus"),
                            ("CHILD", "Child / Satellite Campus"),
                        ],
                        default="CHILD",
                        max_length=10,
                        verbose_name="branch type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Only one branch per organisation may be the default.",
                        verbose_name="is default",
                    ),
                ),
                ("address", models.CharField(max_length=256, verbose_name="address")),
                (
                    "city",
                    models.CharField(db_index=True, max_length=64, verbose_name="city"),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="country"
                    ),
                ),
                (
                    "geo_address",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="GPS address"
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="notifications enabled"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "branch",
                "verbose_name_plural": "branches",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BranchUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("EDITOR", "Editor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "is_org_manager",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is manager"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="cf_users.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "branch user",
                "verbose_name_plural": "branch users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="name"
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="trade / display name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="phone number",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("address", models.CharField(max_length=256, verbose_name="address")),
                (
                    "city",
                    models.CharField(db_index=True, max_length=64, verbose_name="city"),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="country"
                    ),
                ),
                (
                    "geo_address",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="GPS address"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to="org_logos/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "logo_svg",
                    models.TextField(blank=True, null=True, verbose_name="SVG logo"),
                ),
                (
                    "theme_color",
                    models.CharField(
                        blank=True,
                        help_text="Hex colour code, e.g. #4A90D9.",
                        max_length=7,
                        null=True,
                        verbose_name="theme colour",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="notifications enabled"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation",
                "verbose_name_plural": "organisations",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="branch",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="cf_users.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AUDITOR", "Denomination Auditor"),
                            ("OVERSEER", "Regional Overseer / Bishop"),
                            ("ADMIN", "HQ Administrator"),
                        ],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "is_org_manager",
                    models.BooleanField(
                        default=True,
                        help_text="Grants administrative access across this organisation's branches.",
                        verbose_name="is manager",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="is admin"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="cf_users.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation user",
                "verbose_name_plural": "organisation users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationOwner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_record",
                        to="cf_users.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "organization_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organizations",
                        to="cf_users.organizationuser",
                        verbose_name="organisation user",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation owner",
                "verbose_name_plural": "organisation owners",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="cf_users_us_email_64e86c_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="cf_users_us_phone_n_7cd0bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_church_staff"], name="cf_users_us_is_chur_1d1930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchuser",
            index=models.Index(
                fields=["branch", "is_org_manager"],
                name="cf_users_br_branch__0b7d3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="branchuser",
            index=models.Index(
                fields=["user", "is_org_manager"], name="cf_users_br_user_id_bf023a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="branchuser",
            constraint=models.UniqueConstraint(
                fields=("user", "branch"), name="cf_users_branchuser_unique_user_branch"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["country", "city"], name="cf_users_or_country_820a59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["organization", "active"], name="cf_users_br_organiz_4e340f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["organization", "is_default"],
                name="cf_users_br_organiz_d6e630_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("organization", "is_default"),
                name="cf_users_branch_unique_default_branch",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationuser",
            index=models.Index(
                fields=["organization", "is_org_manager"],
                name="cf_users_or_organiz_dbc70b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationuser",
            index=models.Index(
                fields=["user", "is_org_manager"], name="cf_users_or_user_id_acd578_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationuser",
            constraint=models.UniqueConstraint(
                fields=("user", "organization", "role"),
                name="cf_users_organizationuser_unique_user_org_role",
            ),
        ),
    ]
