# Generated by Django 6.0.7 on 2026-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_users', '0002_organization_code_autogen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='name')),
                ('value', models.BigIntegerField(default=0, verbose_name='value')),
            ],
            options={
                'verbose_name': 'code sequence',
                'verbose_name_plural': 'code sequences',
            },
        ),
    ]
