# Generated by Django 6.0.7 on 2026-08-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_users", "0006_alter_user_birth_date_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="birthday_greetings_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, no automatic birthday messages are sent for this branch. Organisation-level must also be enabled.",
                verbose_name="birthday greetings enabled",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="birthday_message",
            field=models.TextField(
                blank=True,
                help_text="Optional branch override for the birthday body. Leave blank to use the organisation message. Placeholders: {name}, {org}, {branch}, {year}.",
                verbose_name="birthday message",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="birthday_subject",
            field=models.CharField(
                blank=True,
                help_text="Optional branch override for the subject. Leave blank to use the organisation text. Placeholders: {name}, {org}, {branch}, {year}.",
                max_length=200,
                verbose_name="birthday subject / title",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="birthday_greetings_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When off, no automatic birthday messages are sent for this organisation.",
                verbose_name="birthday greetings enabled",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="birthday_message",
            field=models.TextField(
                blank=True,
                help_text="Typed body for automatic birthday messages (organisation default). Branches may override. Placeholders: {name}, {org}, {branch}, {year}.",
                verbose_name="birthday message",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="birthday_subject",
            field=models.CharField(
                blank=True,
                help_text="Typed subject/title for automatic birthday messages. Placeholders: {name}, {org}, {branch}, {year}.",
                max_length=200,
                verbose_name="birthday subject / title",
            ),
        ),
    ]
