# Generated by Django 6.0.7 on 2026-08-04 14:20

import cf_users.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="purchase cost"
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="purchase date")),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("UNDER_REPAIR", "Under Repair"),
                            ("DISPOSED", "Disposed / Written Off"),
                        ],
                        db_index=True,
                        default="OPERATIONAL",
                        max_length=20,
                        verbose_name="current status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "asset",
                "verbose_name_plural": "assets",
                "ordering": ("name",),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "depreciation_rate_annual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of asset value depreciated per year.",
                        max_digits=5,
                        verbose_name="annual depreciation rate (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "asset category",
                "verbose_name_plural": "asset categories",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="allocated amount"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "budget",
                "verbose_name_plural": "budgets",
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "job_title",
                    models.CharField(max_length=150, verbose_name="job title"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("PASTORAL", "Pastoral Staff"),
                            ("ADMIN", "Administrative Staff"),
                            ("CONTRACTOR", "External Contractor"),
                            ("VOLUNTEER", "Stipend Volunteer"),
                        ],
                        default="ADMIN",
                        max_length=20,
                        verbose_name="employment type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("TERMINATED", "Terminated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="employment status",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="hire date")),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="termination date"
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base contractual pay amount per pay cycle.",
                        max_digits=15,
                        verbose_name="base salary",
                    ),
                ),
                (
                    "bank_account_details",
                    models.TextField(blank=True, verbose_name="bank account details"),
                ),
            ],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
                "ordering": ("member__last_name", "member__first_name"),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "period_name",
                    models.CharField(max_length=100, verbose_name="period name"),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="is closed"),
                ),
            ],
            options={
                "verbose_name": "financial period",
                "verbose_name_plural": "financial periods",
                "ordering": ("-start_date",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual Vacation"),
                            ("SICK", "Sick Leave"),
                            ("MATERNITY", "Maternity / Paternity"),
                            ("SABBATICAL", "Pastoral Sabbatical"),
                            ("OTHER", "Unpaid / Other Leave"),
                        ],
                        default="ANNUAL",
                        max_length=20,
                        verbose_name="leave type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="reason for leave"),
                ),
            ],
            options={
                "verbose_name": "leave",
                "verbose_name_plural": "leave records",
                "ordering": ("-start_date",),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("pay_period_start", models.DateField(verbose_name="pay period start")),
                ("pay_period_end", models.DateField(verbose_name="pay period end")),
                (
                    "gross_pay",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="gross pay"
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Housing, utility, or ministerial travel allowances.",
                        max_digits=15,
                        verbose_name="allowances",
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax, health insurance, or pension contributions.",
                        max_digits=15,
                        verbose_name="deductions",
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated take-home amount: gross + allowances − deductions.",
                        max_digits=15,
                        verbose_name="net pay",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="payment date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Disbursed / Paid"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "payroll",
                "verbose_name_plural": "payrolls",
                "ordering": ("-pay_period_end",),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        db_index=True,
                        max_length=10,
                        verbose_name="transaction type",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="category")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="amount"
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        unique=True,
                        verbose_name="reference code",
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference from a payment gateway or mobile money provider.",
                        max_length=255,
                        verbose_name="gateway / payment reference",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is approved"
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ("-created_at",),
                "abstract": False,
            },
            bases=(models.Model, cf_users.mixins.ValidateOrgBranchMixin),
        ),
    ]
