# Generated by Django 6.0.7 on 2026-08-04 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_finance', '0003_member_user_composition'),
        ('cf_users', '0002_organization_code_autogen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('fund_type', models.CharField(choices=[('OFFERINGS', 'Offerings'), ('TITHE', 'Tithe'), ('PROJECT', 'Project'), ('CHARITY', 'Charity'), ('BUILDING', 'Building fund'), ('MISSIONS', 'Missions'), ('WELFARE', 'Welfare / benevolence'), ('THANKSGIVING', 'Thanksgiving'), ('FIRST_FRUITS', 'First fruits'), ('PLEDGE', 'Pledge'), ('SEED', 'Seed'), ('OTHER', 'Other')], db_index=True, help_text='Primary classification of this fund.', max_length=20, verbose_name='fund type')),
                ('name', models.CharField(help_text="Display name for this fund, e.g. 'General Tithe' or 'New Auditorium Project'.", max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='cf_users.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name': 'fund',
                'verbose_name_plural': 'funds',
                'ordering': ('fund_type', 'name'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='fund',
            field=models.ForeignKey(blank=True, help_text='Optional church fund this transaction belongs to (e.g. Tithe, Offerings).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cf_finance.fund', verbose_name='fund'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['branch', 'fund_type', 'is_active'], name='cf_finance__branch__594e06_idx'),
        ),
        migrations.AddConstraint(
            model_name='fund',
            constraint=models.UniqueConstraint(fields=('branch', 'fund_type', 'name'), name='cf_finance_fund_unique_branch_type_name'),
        ),
    ]
