# Generated by Django 6.0.7 on 2026-08-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_finance', '0004_fund_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current balance or target amount for this fund.', max_digits=15, verbose_name='amount'),
        ),
    ]
