# Generated by Django 6.0.7 on 2026-08-06 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="last message at",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="social_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="participants",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversation",
                "verbose_name_plural": "conversations",
                "ordering": ("-last_message_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("body", models.TextField(max_length=4000, verbose_name="body")),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is read"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="cf_social.conversation",
                        verbose_name="conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "direct message",
                "verbose_name_plural": "direct messages",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "body",
                    models.TextField(blank=True, max_length=5000, verbose_name="body"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="social/posts/images/%Y/%m/",
                        verbose_name="image",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="social/posts/videos/%Y/%m/",
                        verbose_name="video",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("FOLLOWERS", "Followers only"),
                            ("PRIVATE", "Private"),
                        ],
                        db_index=True,
                        default="PUBLIC",
                        max_length=20,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="likes"),
                ),
                (
                    "comments_count",
                    models.PositiveIntegerField(default=0, verbose_name="comments"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Staff can hide posts without deleting them.",
                        verbose_name="hidden by moderation",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("body", models.TextField(max_length=2000, verbose_name="body")),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="hidden"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="cf_social.comment",
                        verbose_name="parent comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="cf_social.post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="cf_social.post",
                        verbose_name="post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "like",
                "verbose_name_plural": "likes",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("POST", "Post"),
                            ("COMMENT", "Comment"),
                            ("USER", "User / profile"),
                        ],
                        max_length=20,
                        verbose_name="target type",
                    ),
                ),
                ("reason", models.TextField(max_length=2000, verbose_name="reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("REVIEWING", "Reviewing"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(blank=True, verbose_name="staff notes"),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_reports_filed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reporter",
                    ),
                ),
                (
                    "target_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="cf_social.comment",
                        verbose_name="comment",
                    ),
                ),
                (
                    "target_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="cf_social.post",
                        verbose_name="post",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_reports_against",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reported user",
                    ),
                ),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SocialNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("FOLLOW", "New follower"),
                            ("LIKE", "Like"),
                            ("COMMENT", "Comment"),
                            ("MESSAGE", "Direct message"),
                            ("MENTION", "Mention"),
                            ("SYSTEM", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="message")),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is read"
                    ),
                ),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="link"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_notifications_acted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="cf_social.post",
                        verbose_name="post",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "social notification",
                "verbose_name_plural": "social notifications",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="display name"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=1000, verbose_name="bio"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="social/avatars/%Y/%m/",
                        verbose_name="avatar",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="social/covers/%Y/%m/",
                        verbose_name="cover image",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="location"
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("FOLLOWERS", "Followers only"),
                            ("PRIVATE", "Private"),
                        ],
                        db_index=True,
                        default="PUBLIC",
                        max_length=20,
                        verbose_name="profile visibility",
                    ),
                ),
                (
                    "default_post_visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("FOLLOWERS", "Followers only"),
                            ("PRIVATE", "Private"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                        verbose_name="default post visibility",
                    ),
                ),
                (
                    "allow_direct_messages",
                    models.BooleanField(
                        default=True,
                        help_text="When off, only people you follow can message you.",
                        verbose_name="allow direct messages",
                    ),
                ),
                (
                    "show_online_status",
                    models.BooleanField(
                        default=False, verbose_name="show online status"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "social profile",
                "verbose_name_plural": "social profiles",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="blocked user",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_initiated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="blocker",
                    ),
                ),
            ],
            options={
                "verbose_name": "block",
                "verbose_name_plural": "blocks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked"),
                        name="cf_social_block_unique_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("blocker", models.F("blocked")), _negated=True
                        ),
                        name="cf_social_block_no_self",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="follower",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="following",
                    ),
                ),
            ],
            options={
                "verbose_name": "follow",
                "verbose_name_plural": "follows",
                "indexes": [
                    models.Index(
                        fields=["follower", "-created_at"],
                        name="cf_social_f_followe_e989aa_idx",
                    ),
                    models.Index(
                        fields=["following", "-created_at"],
                        name="cf_social_f_followi_62b6e2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "following"),
                        name="cf_social_follow_unique_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follower", models.F("following")), _negated=True
                        ),
                        name="cf_social_follow_no_self",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="cf_social_p_author__0260b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "-created_at"],
                name="cf_social_p_visibil_2406bc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="postlike",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="cf_social_like_unique_post_user"
            ),
        ),
        migrations.AddIndex(
            model_name="socialnotification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="cf_social_s_recipie_c7e206_idx",
            ),
        ),
    ]
