# Generated by Django 6.0.7 on 2026-08-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cf_finance", "0005_fund_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": ("-modified_at", "name"),
                "verbose_name": "asset",
                "verbose_name_plural": "assets",
            },
        ),
        migrations.AlterModelOptions(
            name="assetcategory",
            options={
                "ordering": ("-modified_at", "name"),
                "verbose_name": "asset category",
                "verbose_name_plural": "asset categories",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": (
                    "-modified_at",
                    "member__user__last_name",
                    "member__user__first_name",
                ),
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
            },
        ),
        migrations.AlterModelOptions(
            name="financialperiod",
            options={
                "ordering": ("-modified_at", "-start_date"),
                "verbose_name": "financial period",
                "verbose_name_plural": "financial periods",
            },
        ),
        migrations.AlterModelOptions(
            name="fund",
            options={
                "ordering": ("-modified_at", "fund_type", "name"),
                "verbose_name": "fund",
                "verbose_name_plural": "funds",
            },
        ),
        migrations.AlterModelOptions(
            name="leave",
            options={
                "ordering": ("-modified_at", "-start_date"),
                "verbose_name": "leave",
                "verbose_name_plural": "leave records",
            },
        ),
        migrations.AlterModelOptions(
            name="payroll",
            options={
                "ordering": ("-modified_at", "-pay_period_end"),
                "verbose_name": "payroll",
                "verbose_name_plural": "payrolls",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ("-modified_at",),
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
            },
        ),
    ]
