# Generated by Django 6.0.7 on 2026-08-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cf_communications", "0002_birthday_greeting_log"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ("-updated_at", "-created_at"),
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
            },
        ),
    ]
