# Generated by Django 6.0.7 on 2026-08-06 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_communications", "0001_initial_from_operations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthdayGreetingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(db_index=True, verbose_name="year"),
                ),
                (
                    "for_date",
                    models.DateField(
                        help_text="The calendar date (this year) the greeting was for.",
                        verbose_name="birthday date",
                    ),
                ),
                (
                    "channel_summary",
                    models.CharField(
                        blank=True,
                        help_text="e.g. email,inapp",
                        max_length=120,
                        verbose_name="channels used",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="sent at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birthday_greeting_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "birthday greeting log",
                "verbose_name_plural": "birthday greeting logs",
                "ordering": ("-sent_at",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "year"),
                        name="cf_communications_birthdaygreetinglog_unique_user_year",
                    )
                ],
            },
        ),
    ]
