# Generated by Django 6.0.7 on 2026-08-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf_users", "0003_code_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("VIEWER", "Viewer / Member"),
                    ("AUDITOR", "Denomination Auditor"),
                    ("OVERSEER", "Regional Overseer / Bishop"),
                    ("ADMIN", "HQ Administrator"),
                ],
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
