# Generated by Django 6.0.7 on 2026-08-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cf_people", "0003_member_user_composition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="member",
            name="join_date",
        ),
    ]
