# Generated by Django 6.0.7 on 2026-08-06 12:59
# Made idempotent: skip DB rename when group_type already exists.

import django.db.models.deletion
from django.db import migrations, models


def _cols(schema_editor, table: str) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        desc = connection.introspection.get_table_description(cursor, table)
    return {c.name if hasattr(c, "name") else c[1] for c in desc}


def ensure_group_type(apps, schema_editor):
    table = "cf_people_subbranch"
    cols = _cols(schema_editor, table)
    if "group" in cols and "group_type" not in cols:
        schema_editor.execute(
            f'ALTER TABLE {table} RENAME COLUMN "group" TO group_type;'
        )
    # If neither exists (shouldn't happen), add group_type.
    cols = _cols(schema_editor, table)
    if "group_type" not in cols:
        schema_editor.execute(
            f"ALTER TABLE {table} ADD COLUMN group_type varchar(20) "
            f"NOT NULL DEFAULT 'CELL';"
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cf_people", "0004_remove_member_gender_remove_member_join_date"),
        ("cf_users", "0005_user_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subbranch",
            options={
                "ordering": ("name",),
                "verbose_name": "sub group",
                "verbose_name_plural": "sub groups",
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_group_type, noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="subbranch",
                    name="group",
                ),
                migrations.AddField(
                    model_name="subbranch",
                    name="group_type",
                    field=models.CharField(
                        choices=[
                            ("ZONE", "Zone"),
                            ("CELL", "Cell Group"),
                            ("SETTLITE", "Settlite Fellowship"),
                        ],
                        default="CELL",
                        max_length=20,
                        verbose_name="group type",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="subbranch",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_groups",
                to="cf_users.branch",
                verbose_name="branch",
            ),
        ),
        migrations.AlterField(
            model_name="subbranch",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_sub_groups",
                to="cf_people.member",
                verbose_name="leader",
            ),
        ),
    ]
