# Generated by Django 6.0.7 on 2026-08-06 14:09
# Copy Member.date_of_birth → User.birth_date when user has none, then drop field.

from django.db import migrations


def copy_member_dob_to_user(apps, schema_editor):
    Member = apps.get_model("cf_people", "Member")
    User = apps.get_model("cf_users", "User")
    for member in Member.objects.exclude(date_of_birth__isnull=True).select_related(
        "user"
    ).iterator():
        user = member.user
        if user is None:
            continue
        if getattr(user, "birth_date", None) is None and member.date_of_birth:
            User.objects.filter(pk=user.pk).update(birth_date=member.date_of_birth)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cf_people", "0007_zone_unique_branch_name_code"),
        ("cf_users", "0006_alter_user_birth_date_gender"),
    ]

    operations = [
        migrations.RunPython(copy_member_dob_to_user, noop),
        migrations.RemoveField(
            model_name="member",
            name="date_of_birth",
        ),
    ]
